{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  host: {{ .Values.route.hostname }}.{{ .Values.route.hostnamesuffix }}
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ template "common.names.fullname" . }}
    weight: 100
  wildcardPolicy: None
{{- end }}
